### PR TITLE
#1- Solved for PDF not for TEXT as of now

### PR DESCRIPTION
**Pull request by Vaarun-Kamath**
solved for pdf not for text as of now

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
@Vaarun-Kamath what error is this related to and can you send a screen shot of the working?

**Comment by Vaarun-Kamath** [comment]
image

**Comment by Vaarun-Kamath** [comment]
this is for #1

**Comment by Mohamed-Ayaan358** [comment]
@Vaarun-Kamath Are you doing a new PR or should I merge this one?

**Comment by Mohamed-Ayaan358** [comment]
DW you have done well and marks will be given :)

**Comment by Mohamed-Ayaan358** [comment]
!bounty 50

**Comment by Vaarun-Kamath** [comment]
Hey why does it say NOT-PARTICIPATING in the hacktober website? This issue is marked as hacktober right?

**Comment by anuragrao04** [comment]
This repo did not have hacktoberfest tags, nor did the PR, so it was not counted for hacktober. Do let the maintainer know about these issues in advance the next time. Nothing can be done now since hacktober is over :(

**Pull request merged**
