### PR TITLE
feat: add GUI and feature to compare ppt, png and jpg files

### PR DESCRIPTION
**Pull request by samarth777**

### CODE REVIEW

**Comment by samarth777** [comment]
can you merge this PR

**Comment by Mohamed-Ayaan358** [comment]
Pls screenshots and ill see what i can do

**Comment by samarth777** [comment]
image
image
image
image
image

**Comment by Mohamed-Ayaan358** [comment]
good job

**Comment by Mohamed-Ayaan358** [comment]
!bounty 60

**Pull request merged**
