### PR TITLE
gui to upload

### PR DESCRIPTION
**Pull request by tnayagarwal**
simple gui to upload files not to compare

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
@tnayagarwal Can you send me a screenshot of how the GUI looks? 

Do note that the update you've made is relatively small, so we will have to see if total points can be assigned. I would suggest looking into a web dev aspect or including a feature along with the gui.

**Comment by tnayagarwal** [comment]
@Mohamed-Ayaan358 its all i could do, even 1/4th of the points are okay 
my srn is PES2202200695

**Comment by Mohamed-Ayaan358** [comment]
> @Mohamed-Ayaan358 its all i could do, even 1/4th of the points are okay my srn is PES2202200695

Ok do send a screenshot.

**Comment by Mohamed-Ayaan358** [comment]
@tnayagarwal

**Pull request closed without merging**
