### PR TITLE
Major UI changes #1

### PR DESCRIPTION
**Pull request by SarthakSKumar**
Sarthak S Kumar
PES2UG21CS482
Fixes: #1

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
Can you get screenshot of what this looks like.

**Comment by SarthakSKumar** [comment]
image

**Comment by SarthakSKumar** [comment]
Please review @Mohamed-Ayaan358

**Comment by Mohamed-Ayaan358** [comment]
!bounty 25

**Pull request merged**
