### PR TITLE
error.py

### LINKED ISSUE #3: Find a more efficient and accurate way to find errors in a pdf
At the moment this script just tells the differences between one pdf and another pdf ,this total is given as mistakes.

### PR DESCRIPTION
**Pull request by pranjalitalanki**
@Mohamed-Ayaan358  resolved #3

### CODE REVIEW

**Comment by pranjalala** [comment]
@Mohamed-Ayaan358  looking forward to a review!

**Comment by Mohamed-Ayaan358** [comment]
Ok starters I'm going to need a screenshot of it working, second is it compatible with the new code that has been merged? (i.e: The tkinter module code) and show proof of that

**Comment by pranjalala** [comment]
here is the screen shot of the working code 
[ren cude doc scan.docx](https://github.com/acmpesuecc/Doc-Scan/files/9841638/ren.cude.doc.scan.docx)

**Comment by pranjalala** [comment]
I haven't checked whether the new code is compatible with the previous one. will check and let you know in a while 
thanks!

**Comment by Mohamed-Ayaan358** [comment]
@pranjalala Please do give an update soon, or I may be forced to give another individual the access.

**Pull request closed without merging**
